  import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import CartHydrator from "@/components/cart/CartHydrator";
  import { NextIntlClientProvider } from "next-intl";
  import { routing } from "@/i18n/routing";
import { locale } from "next/root-params";
import LanguageSelector from "@/components/LanguageSelector";
import { Suspense } from "react";

  export function generateStaticParams() {
    return routing.locales.map((l) => ({ locale: l }));
  } 

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default async function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
   const lang = await locale();
    
    return (
      <html
        lang={lang}
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex items-center justify-center flex-col">
          <CartHydrator />
          <NextIntlClientProvider>
           <Suspense fallback={<div style={{ background: "red", width: 100, height: 30 }} />}>
            <LanguageSelector />
          </Suspense>
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    );
  }
